version: '3'
services:
  emulator:
    build: .
    #environment:
    #  OT_EMULATOR_smoothie: '{"right": {"model": "p300_single_gen2"}, "left": {"model": "p300_single_gen2"}}'
    command: python3 -m opentrons.hardware_control.emulation.app
    ports:
      - '8888:8888'
      - '9000:9000'
      - '9002:9002'
      - '9003:9003'
      - '9004:9004'
      - '9995:9995'
      - '9997:9997'
      - '9998:9998'
      - '9999:9999'
    networks:
      - container-network
  smoothie:
    build: .
    command: python3 -m opentrons.hardware_control.emulation.scripts.run_smoothie
    ports:
      - '9996:9996'
    # Uncomment lines below to override the pipette(s) loaded by emulator
    environment:
      OT_EMULATOR_smoothie: '{"right": {"model": "p1000_single"}, "left": {"model": "p300_single_custom"}}'
    networks:
      - container-network
  robot-server:
    build: .
    #command:
    command:
      - /bin/sh
      - -c
      - |
        pip install -e /data/otapi
        uvicorn "robot_server:app" --host 0.0.0.0 --port 31950 --ws wsproto
    ports:
      - '31950:31950'
      - '4444:4444'
    environment:
      OT_API_CONFIG_DIR: /data
      OT_SMOOTHIE_EMULATOR_URI: socket://smoothie:9996
      OT_EMULATOR_module_server: '{"host": "emulator"}'
      OT_SHARED_DATA_PATH: /data/otapi/otapi/robot_overrides/ot_shared_data
      OTAPI_BASE_DIR: /data/otapi/otapi
      #OT_API_LABWARE_USER_DEFINITIONS_DIR_V2: /otapi/otapi/ot_custom_labware

    networks:
      - container-network
    depends_on:
      - 'emulator'
      - 'smoothie'
    volumes:
      - /Users/Dennis/Documents/repos/otapi/otapi/robot_overrides/ot_docker_config:/data:rw
      - /Users/Dennis/Documents/repos/otapi/otapi/robot_overrides/ot_docker_config:/config:rw
      - /Users/Dennis/Documents/repos/otapi:/data/otapi
#  tempdeck:
#    build: .
#    command: python3 -m opentrons.hardware_control.emulation.scripts.run_module_emulator tempdeck emulator
#    networks:
#      - container-network
#    depends_on:
#      - 'emulator'
#  thermocycler:
#    build: .
#    command: python3 -m opentrons.hardware_control.emulation.scripts.run_module_emulator thermocycler emulator
#    networks:
#      - container-network
#    depends_on:
#      - 'emulator'
#  magdeck:
#    build: .
#    command: python3 -m opentrons.hardware_control.emulation.scripts.run_module_emulator magdeck emulator
#    networks:
#      - container-network
#    depends_on:
#      - 'emulator'
#  heatershaker:
#    build: .
#    command: python3 -m opentrons.hardware_control.emulation.scripts.run_module_emulator heatershaker emulator
#    networks:
#      - container-network
#    depends_on:
#      - 'emulator'

networks:
  container-network:
