name: "Setup All Environments"
description: "Set up the environments to handle a monorepo python projects"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - shell: bash
      run: |
        npm install --global shx@0.3.3
    - uses: 'actions/setup-python@v4'
      id: python38
      with:
        python-version: '3.8'
        cache: "pipenv"
        cache-dependency-path: |
          **/setup.*
          **/Pipfile.*
    - name: Set the OT_PYTHON env variable
      shell: bash
      run: echo "OT_PYTHON=$(which python)" >> $GITHUB_ENV
    - shell: bash
      name: install pipenv on 3.8
      run: $OT_PYTHON -m pip install pipenv==2021.5.29
    - shell: bash
      if: steps.python38.outputs.cache-hit == 'false'
      working-directory: environments
      name: setup venv python 3.8
      run: make -C ot-3 setup
    - uses: 'actions/setup-python@v4'
      id: python310
      with:
        python-version: '3.10'
        cache: "pipenv"
        cache-dependency-path: |
          **/setup.py
          **/Pipfile.*
    - name: Set the OT_PYTHON env variable
      shell: bash
      run: echo "OT_PYTHON=$(which python)" >> $GITHUB_ENV
    - shell: bash
      name: install pipenv on 3.10
      run: $OT_PYTHON -m pip install pipenv==2021.5.29
    - shell: bash
      if: steps.python310.outputs.cache-hit == 'false'
      working-directory: environments
      name: setup the environments
      run: |
        make -C ot-2 setup
        make -C dev setup
        make -C app setup
