name: 'Python Setup'
description: 'Set up the environment to handle a monorepo python project'
inputs:
  project:
    description: 'Which project (by subdirectory) to set up'
    required: true
  python-version:
    description: "What Python version to use to create the project's virtual environment"
    required: false
    default: "false"
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - name: Set the OT_PYTHON env variable
      shell: bash
      run: echo "OT_PYTHON=$(which python)" >> $GITHUB_ENV
    - name: If provided set the OT_VIRTUALENV_VERSION env variable
      shell : bash
      if: ${{ inputs.python-version != 'false' }}
      # beta and rc versions of python have appendage of -
      # cut it off
      run: |
        version=$(echo ${{ inputs.python-version }} | cut -d- -f1)
        echo "OT_VIRTUALENV_VERSION=$version" >> $GITHUB_ENV
    - shell: bash
      run: |
        npm install --global shx@0.3.3
        $OT_PYTHON -m pip install pipenv==2021.5.29
    - shell: bash
      run: 'make -C ${{ inputs.project }} setup'
