# This workflow runs test and lint on branch pushes that touch the
# robot-server project or its dependencies

name: 'Robot server lint/test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'api/**/*'
      - 'hardware/**/*'
      - 'Makefile'
      - 'shared-data/**/*'
      - '!shared-data/js/**/*'
      - 'robot-server/**/*'
      - 'notify-server/**/*'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/robot-server-test-lint.yaml'
      - '.github/actions/python/**'
    branches:
      - 'edge'
      - 'release'
      - '*hotfix*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'api/**/*'
      - 'hardware/**/*'
      - 'Makefile'
      - 'shared-data/**/*'
      - '!shared-data/js/**/*'
      - 'robot-server/**/*'
      - 'notify-server/**/*'
      - 'scripts/**/*.mk'
      - 'scripts/**/*.py'
      - '.github/workflows/robot-server-test-lint.yaml'
      - '.github/actions/python/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.ref_name != 'edge' || github.run_id}}-${{ github.ref_type != 'tag' || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'robot server package linting and tests'
    timeout-minutes: 20
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        with-ot-hardware: ['true', 'false']
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '14'
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'

      - uses: './.github/actions/python/setup'
        with:
          project: 'robot-server'
      - if: ${{ matrix.with-ot-hardware == 'false' }}
        name: Remove OT-3 hardware package
        run: make -C robot-server setup-ot2
      - name: Lint
        run: make -C robot-server lint
      - name: Test
        run: make -C robot-server test-cov
      - name: Ensure assets build
        run: make -C robot-server sdist wheel
      - name: Upload coverage report
        uses: 'codecov/codecov-action@v3'
        with:
          files: ./robot-server/coverage.xml
          flags: robot-server
