name: "Python Setup"
description: "Set up the environment to handle a monorepo python project"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "${OSTYPE}" =~ "linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsystemd-dev
        fi
    - shell: bash
      run: |
        npm install --global shx@0.3.3
    - shell: bash
      name: make setup-py
      run: make setup-py-faster
